### ISSUE TITLE
"Don't know how to handle JumpToError"

### ISSUE THREAD

**Issue by tomsmeding** [ashinkarov/nvim-agda#10]
I'm probably doing something wrong, but I just installed `nvim-agda` (using [vim-plug](https://github.com/junegunn/vim-plug)) as well as `lua-utf8` for lua 5.1, but loading (`<localleader>l`) a file containing an error produces the error message in the title.

Terminal session recording here: https://asciinema.org/a/0iRhEVSdTfPNj4KZEbPdwbthb

OS: Arch Linux
nvim: v0.8.3

**Comment by ashinkarov** [comment]
Ok, it is an option now.

**Comment by tomsmeding** [comment]
Yep, that fixes it! Thanks for the quick fix :)

Turns out I prefer the separate-window interface of a different plugin (which unfortunately has less command coverage). I'll see what I do.

**Comment by ashinkarov** [comment]
@tomsmeding , what is exactly meant by separate-window here?  Most of the things are in the floating window, and the rest is available throug `:messges`.  Anyhow, the plugin is quite straight-forward to hack, it is quite simple, so feel free to send a pull request.  At the end of the day, I presume it is just about figuring out where do you want to print things to, which is close to trivial to change.
