### ISSUE TITLE
Can't find lua-utf8

### ISSUE THREAD

**Issue by WinstonMDP** [ashinkarov/nvim-agda#11]
![screen-1689343098](https://github.com/ashinkarov/nvim-agda/assets/61916541/721eedbc-185b-445d-9a48-4c8508301f11)

Arch. Install over pacman lua-luautf8 0.1.5-2

**Comment by ashinkarov** [comment]
Hi, it seems that this is a version compatibility problem.  Nvim uses lua 5.1, so if your system-wide install uses other versions of lua, then surely neovim will fail to locate it.  Also, your picture shows all the paths that neovim is searching at.  Make sure that the install path of lua-utf8 matches one of the search paths from the picture.  However, I would bet that this is a library version problem.

**Comment by liamwh** [comment]
Using luarocks, you can specify the lua-version to 5.1 like so:

> luarocks --lua-version=5.1 install luautf8 --local

Then you can also add your lua paths to neovim like so:

> local home = os.getenv("HOME")
package.path = package.path .. ";"
    .. home .. "/.luarocks/share/lua/5.1/?.lua;"
    .. home .. "/.luarocks/share/lua/5.1/?/init.lua;"
package.cpath = package.cpath .. ";"
    .. home .. "/.luarocks/lib/lua/5.1/?.so;"

Does this resolve your issue @WinstonMDP?

**Comment by WinstonMDP** [comment]
Unfortunately, I no longer use agda. so I can't check. I will close this issue.
